### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by setrin** [OSRSB/OsrsBot#136]
**BEFORE REPORTING**
Ensure RuneLite is up to date in IDE and you are using the latest version of the master branch

**Describe the bug**
I get this error a lot. It's not consistent enough for me to debug it. Sometimes it happens after few minutes of my script running, sometimes it happens immediately after script start
`2022-03-15 16:09:21 [Script-Oak Chopper] WARN  rsb.script.Script - Uncaught exception from script:
java.lang.NullPointerException: Cannot read field "fh" because "this.s" is null
        at oj.c(oj.java:26)
        at el.xl(el.java)
        at oj.get(oj.java:20177)
        at jz.getParentId(jz.java:51851)
        at jz.getParent(jz.java:17226)
        at rsb.wrappers.RSWidget.<init>(RSWidget.java:38)
        at rsb.methods.Interfaces.getComponent(Interfaces.java:63)
        at rsb.methods.Inventory.getInterface(Inventory.java:38)
        at rsb.methods.Inventory.getItems(Inventory.java:656)
        at rsb.methods.Inventory.getCount(Inventory.java:965)
        at rsb.methods.Inventory.getCount(Inventory.java:953)
        at rsb.methods.Inventory.isFull(Inventory.java:314)
        at OakChopper.getState(OakChopper.java:75)
        at OakChopper.loop(OakChopper.java:132)
        at rsb.script.Script.run(Script.java:272)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-03-15 16:09:21 [Script-Oak Chopper] INFO  rsb.script.Script - Script stopped.`

**To Reproduce**
I check in loop if the inventory is full and based on it script decides what to do (bank, chop tree or walk)

**Expected behavior**
It works reliably

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by dginovker** [comment]
I get this too, so as a temporary fix I threw my check in a try/catch. It's mostly harmless, but widgets are a bit wonky in the API

**Comment by setrin** [comment]
Why haven't i think of it :D thanks, will do it like that

**Comment by GigiaJ** [comment]
Have you looked into the debug call stack or reflectively checked the types and such for that?

**Comment by setrin** [comment]
if that's a question for me, then no. I tried to back trace the error, but i'm not so good with Java and much less good with this project :D

**Comment by myzsqn** [comment]
Hitting a similar issue on isVisible:
```
java.lang.NullPointerException: Cannot read field "fh" because "this.s" is null
	at oj.c(oj.java:26)
	at el.xl(el.java)
	at oj.get(oj.java:20177)
	at jz.getParentId(jz.java:51851)
	at jz.getParent(jz.java:17226)
	at jz.isHidden(jz.java:38466)
	at rsb.wrappers.RSWidget.isVisible(RSWidget.java:54)
	at rsb.methods.Inventory.isOpen(Inventory.java:57)
	at rsb.methods.Inventory.getInterface(Inventory.java:45)
	at rsb.methods.Inventory.getItems(Inventory.java:656)
	at rsb.methods.Inventory.getCount(Inventory.java:965)
	at rsb.methods.Inventory.getCount(Inventory.java:953)
	at rsb.methods.Inventory.isFull(Inventory.java:314)
	at com.myz.ZFisher.getState(ZFisher.java:97)
	at com.myz.ZFisher.loop(ZFisher.java:129)
	at rsb.script.Script.run(Script.java:272)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by setrin** [comment]
I get similar error with another cause. This one happened when bot tried to stash all items into bank.
```
2022-03-16 13:03:37 [Client] ERROR client-patch - Client error: null
java.lang.NullPointerException: Cannot read field "fh" because "this.s" is null
	at oj.c(oj.java:26)
	at el.xl(el.java)
	at client.sh(client.java:3858)
	at dz.ja(dz.java)
	at dz.ja(dz.java:11190)
	at dz.ja(dz.java:11189)
	at dz.ja(dz.java:11189)
	at dz.ja(dz.java:11189)
	at dy.jx(dy.java:10724)
	at dz.ja(dz.java:11208)
	at dz.ja(dz.java:11189)
	at dz.ja(dz.java:11189)
	at dz.ja(dz.java:11189)
	at dy.jx(dy.java:10724)
	at client.vm(client.java:3210)
	at client.b(client.java:965)
	at al.d(al.java:344)
	at al.run(al.java:323)
	at java.base/java.lang.Thread.run(Thread.java:833)
error_game_crash
```
